#!/bin/bash --norc

# Copyright (c) 2016, the Dart Team. All rights reserved. Use of this
# source code is governed by a BSD-style license that can be found in
# the LICENSE file.

# Run the stand-alone transformer on a single test. This script is very
# simple and not very flexible; it is intended to allow for tranformation
# independently of `pub`, which enables interactive debugging and similar
# modern conveniencies. Because of its simplicity, this script must be
# executed from the root of this package (that is, `cd ..`), which is
# the same working directory that is required for running `pub`
# commands.
#
# Invocation: tool/transform test/<name_of_test_file> ..

# Note that the value of DART_VM_OPTIONS is included in the options
# given to `dart`, similarly to the treatment of the same variable in
# invocations of `pub`.

function usage {
  echo 'Usage: tool/transform <test_files>..'
}

if [ ! -e pubspec.yaml ]; then
  echo "Expected to find the file 'pubspec.yaml'. Please run from the"
  echo "directory 'test_reflectable'."
  echo
  usage
  exit -1
fi

if ! grep test_reflectable pubspec.yaml >/dev/null; then
  echo "Expected to run from the directory 'test_reflectable' in the"
  echo "package 'reflectable'. Please change directory and retry."
  usage
  exit -1
fi

if [ ! -e build/test/packages ]; then
  echo "Expected to find 'build/test/packages'. Please make sure that"
  echo "a command like \`pub build --mode=debug <your_source_directory>\`"
  echo "has been executed such that this directory has been created."
  echo
  usage
  exit -1
fi

TRANSFORMER=../reflectable/bin/reflectable_transformer.dart
dart $DART_VM_OPTIONS $TRANSFORMER test_reflectable "$@"

