#!/bin/bash --norc

# Copyright (c) 2015, the Dart Team. All rights reserved. Use of this
# source code is governed by a BSD-style license that can be found in
# the LICENSE file.

PACKAGE_ROOT=../test/packages

for n in ..{,/build}/test/*_test.dart; do
  echo "---------- $(basename $n)"
  dart --package-root=$PACKAGE_ROOT $n
done

