#!/bin/bash --norc

# Copyright (c) 2015, the Dart Team. All rights reserved. Use of this
# source code is governed by a BSD-style license that can be found in
# the LICENSE file.

function run_dart {
  echo "---------- $(basename $n)"
  if dart --checked --package-root="$1/test/packages" $n; then true; else
    SUMMARY="$SUMMARY
  $n"
  fi
}

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

cd $DIR/..
pub get
pub build --mode=debug test

SUMMARY=""
for n in $DIR/../test/*_test.dart; do run_dart $DIR/..; done
for n in $DIR/../build/test/*_test.dart; do run_dart $DIR/../build; done

echo "---------- Failed tests:$SUMMARY"

