#!/bin/bash --norc

# Copyright (c) 2015, the Dart Team. All rights reserved. Use of this
# source code is governed by a BSD-style license that can be found in
# the LICENSE file.

function run_dart {
  echo "---------- $(basename $n)"
  if dart --checked $n; then true; else
    SUMMARY="$SUMMARY
  $n"
  fi
}

SUMMARY=""
for n in ../test/*_test.dart; do run_dart ..; done
for n in ../build/test/*_test.dart; do run_dart ../build; done

echo "---------- Failed tests:$SUMMARY"
