#!/bin/bash --norc
# Copyright (c) 2015, the Dart Team. All rights reserved. Use of this
# source code is governed by a BSD-style license that can be found in
# the LICENSE file.

OPTIONS="--package-root=../packages"
XFORM_DIR="../test/to_be_transformed"
BUILD_DIR="../build/test/to_be_transformed"

for n in $XFORM_DIR/*_test.dart $BUILD_DIR/*_test.dart; do
  fname=${n##*/}
  if [ ! "${fname:0:4}" = "bad_" ]; then
    echo "-------------------- ${n:3}"
    dart $OPTIONS $n
  fi
done
