name: coverage_reflectable
version: 2.0.0-dev.2.0
description: >
  A simple tool for measuring code coverage in the reflectable transformer when
  transforming all tests in 'test_reflectable/test'. Only useful for developers
  of reflectable. Note that it is necessary to use `path:` dependencies in order
  to depend on observatory, because observatory has not been made available as
  a separate package; any concrete usage of this package entails downloading the
  sdk separately and adjusting the paths for the concrete setup.
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  observatory:
    path: ../../sdk/runtime/observatory
  observe: any
  analyzer: any
dependency_overrides:
  analyzer:
    path: ../../sdk/third_party/observatory_pub_packages/packages/analyzer
  args:
    path: ../../sdk/third_party/observatory_pub_packages/packages/args
  async:
    path: ../../sdk/third_party/observatory_pub_packages/packages/async
  barback:
    path: ../../sdk/third_party/observatory_pub_packages/packages/barback
  browser:
    path: ../../sdk/third_party/observatory_pub_packages/packages/browser
  charcode:
    path: ../../sdk/third_party/observatory_pub_packages/packages/charcode
  charted:
    path: ../../sdk/third_party/observatory_pub_packages/packages/charted
  cli_util:
    path: ../../sdk/third_party/observatory_pub_packages/packages/cli_util
  code_transformers:
    path: ../../sdk/third_party/observatory_pub_packages/packages/code_transformers
  collection:
    path: ../../sdk/third_party/observatory_pub_packages/packages/collection
  csslib:
    path: ../../sdk/third_party/observatory_pub_packages/packages/csslib
  dart_style:
    path: ../../sdk/third_party/observatory_pub_packages/packages/dart_style
  glob:
    path: ../../sdk/third_party/observatory_pub_packages/packages/glob
  html:
    path: ../../sdk/third_party/observatory_pub_packages/packages/html
  initialize:
    path: ../../sdk/third_party/observatory_pub_packages/packages/initialize
  intl:
    path: ../../sdk/third_party/observatory_pub_packages/packages/intl
  logging:
    path: ../../sdk/third_party/observatory_pub_packages/packages/logging
  matcher:
    path: ../../sdk/third_party/observatory_pub_packages/packages/matcher
  observe:
    path: ../../sdk/third_party/observatory_pub_packages/packages/observe
  package_config:
    path: ../../sdk/third_party/observatory_pub_packages/packages/package_config
  path:
    path: ../../sdk/third_party/observatory_pub_packages/packages/path
  petitparser:
    path: ../../sdk/third_party/observatory_pub_packages/packages/petitparser
  plugin:
    path: ../../sdk/third_party/observatory_pub_packages/packages/plugin
  polymer:
    path: ../../sdk/third_party/observatory_pub_packages/packages/polymer
  polymer_expressions:
    path: ../../sdk/third_party/observatory_pub_packages/packages/polymer_expressions
  polymer_interop:
    path: ../../sdk/third_party/observatory_pub_packages/packages/polymer_interop
  pool:
    path: ../../sdk/third_party/observatory_pub_packages/packages/pool
  quiver:
    path: ../../sdk/third_party/observatory_pub_packages/packages/quiver
  smoke:
    path: ../../sdk/third_party/observatory_pub_packages/packages/smoke
  source_maps:
    path: ../../sdk/third_party/observatory_pub_packages/packages/source_maps
  source_span:
    path: ../../sdk/third_party/observatory_pub_packages/packages/source_span
  stack_trace:
    path: ../../sdk/third_party/observatory_pub_packages/packages/stack_trace
  string_scanner:
    path: ../../sdk/third_party/observatory_pub_packages/packages/string_scanner
  template_binding:
    path: ../../sdk/third_party/observatory_pub_packages/packages/template_binding
  unittest:
    path: ../../sdk/third_party/observatory_pub_packages/packages/unittest
  usage:
    path: ../../sdk/third_party/observatory_pub_packages/packages/usage
  utf:
    path: ../../sdk/third_party/observatory_pub_packages/packages/utf
  watcher:
    path: ../../sdk/third_party/observatory_pub_packages/packages/watcher
  web_components:
    path: ../../sdk/third_party/observatory_pub_packages/packages/web_components
  when:
    path: ../../sdk/third_party/observatory_pub_packages/packages/when
  which:
    path: ../../sdk/third_party/observatory_pub_packages/packages/which
  yaml:
    path: ../../sdk/third_party/observatory_pub_packages/packages/yaml
