include: package:lints/recommended.yaml
linter:
  rules:
    await_only_futures: true
    unnecessary_library_name: false
    omit_local_variable_types: false
    omit_obvious_local_variable_types: true
    specify_nonobvious_local_variable_types: true
