builders:
  reflectable:
    target: ":reflectable"
    import: "package:reflectable/reflectable_builder.dart"
    builder_factories: ["reflectableBuilder"]
    build_extensions: {".dart": [".reflectable.dart"]}
    auto_apply: root_package
    defaults:
      generate_for:
        exclude:
        - lib/**.dart
