#!/bin/bash --norc

# Copyright (c) 2015, the Dart Team. All rights reserved. Use of this
# source code is governed by a BSD-style license that can be found in
# the LICENSE file.

TEST_DIR=../test/mock_tests
PACKAGE_ROOT=../test/packages

for n in $TEST_DIR/*.dart; do
  echo "---------- $(basename $n)"
  dart --package-root=$PACKAGE_ROOT $n
done

