name: reflectable
version: 5.0.1
description: >
  Reflection support based on code generation, using 'capabilities' to
  specify which operations to support, on which objects. This is the
  run-time part of reflectable.
homepage: https://github.com/google/reflectable.dart
environment:
  sdk: ^3.9.0
resolution: workspace
dependencies:
dev_dependencies:
  lints: ^5.0.0
